# List the start up tasks. Learn more https://www.gitpod.io/docs/config-start-tasks/
tasks:
  - name: Install Lean
    command: |
      curl https://raw.githubusercontent.com/leanprover/elan/master/elan-init.sh -sSf | sh -s -- --default-toolchain leanprover/lean4:4.13.0-rc3 -y
      echo 'export PATH="$HOME/.elan/bin:$PATH"' >> $HOME/.bashrc
      source "$HOME/.bashrc"
      lake exe get cache
      echo '### Je kan nu PerfecteGetallen.lean openen'

vscode:
  extensions:
    - leanprover.lean4